### ISSUE TITLE
Project content not showing in light mode 

### ISSUE THREAD

**Issue by kayode96-max** [Ahsankhalid618/SkillSync#2]
![Screenshot_20241021-012711](https://github.com/user-attachments/assets/2b21cfc0-4779-4e7e-99f6-548b0e69f92b)
![Screenshot_20241021-012654](https://github.com/user-attachments/assets/b1b5ab4e-e13f-4416-9025-7644e21756cb)
 I'll like to fix the text color across different themes 
Please assign this to me

**Comment by Ahsankhalid618** [comment]
@kayode96-max alright, Just make sure to fork this repo, create a new branch, make your changes, and then open a PR, also before you open a PR, post your changes screenshot here. Go ahead.

**Comment by AkhilxRawat** [comment]
I would like to work on it please assign

**Comment by kayode96-max** [comment]
Hi @Ahsankhalid618 
I'm trying to work on the app I have made the changes I want to but can't run dev cause of environmental variables (screenshot attached) 
This is my first time participating in open source and I'll be glad if you can put me through how to go about it ![Screenshot_20241024-041402.png](https://github.com/user-attachments/assets/cf74b2ce-2e14-461e-b61f-1439c04f0453)

Thank you

**Comment by Ahsankhalid618** [comment]
@kayode96-max add a .env file at the root of the project and add the env variables there.

These are example env variables, you need to add your own.

GITHUB_ID= (Login to Github, go to developer setting, go to Oauth Apps and create a new app, get Id and Secret.)
GITHUB_SECRET=(Login to Github, go to developer setting, go to Oauth Apps and create a new app, get Id and Secret.)
NEXTAUTH_URL=http://localhost:3000
AUTH_SECRET=(google it, simply just generate random string for next auth secret)

UPLOADTHING_SECRET= (go to uploadthing website and register and collect Secret and App ID)
UPLOADTHING_APP_ID= (go to uploadthing website and register and collect Secret and App ID)

MONGO_URI= Use MongoDB Atlas for generating Mongo URI,

**Comment by kayode96-max** [comment]
Thanks 
I've been able to get all the variables in the env.local file the run dev is working now but I don't get responses when I click sign in with GitHub 
I don't know what to do

**Comment by Ahsankhalid618** [comment]
Register your app with Github Oauth and change the callback URL of github Auth as given on Github.

**Comment by kayode96-max** [comment]
dear @Ahsankhalid618 
Thank you very much for your guide through running the app on my local environment 
I have been able to fix the issue finally and opened a pull request 
kindly check it out and possibly merge 
if there are any adjustments I'm open to taking them

**Comment by kayode96-max** [comment]
![dark font color](https://github.com/user-attachments/assets/759fc90a-b350-4f70-84b2-3bb090c48df3)
![font color](https://github.com/user-attachments/assets/abb0b373-1765-4e6a-9278-0de48e97386d)
